version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: articlefilter-app
    ports:
      - "3000:3000" # Пробрасываем порт для Node.js
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=1237admin_access
      - DB_NAME=articles_db
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: articlefilter-db
    ports:
      - "5433:5432" # Пробрасываем порт PostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1237admin_access
      POSTGRES_DB: articles_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
